#!/usr/bin/env python3
"""Fix JSON files generated by subagents - handle truncation and encoding issues."""
import json
import re
import sys
import os

def fix_json_file(filepath):
    """Attempt to fix and validate a JSON file."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Try to parse as-is first
    try:
        data = json.loads(content)
        print(f"✅ {os.path.basename(filepath)}: Valid JSON, {len(data)} schools")
        return data
    except json.JSONDecodeError as e:
        print(f"⚠️  {os.path.basename(filepath)}: {e}")
    
    # Fix common issues:
    # 1. Replace literal newlines inside strings with \n
    # We need to be careful - only fix newlines that are inside JSON string values
    
    # Strategy: try to find the last complete object and truncate
    # First fix any unescaped newlines in strings
    fixed = content
    
    # Try parsing incrementally - find the last valid closing bracket
    for end_pos in range(len(fixed), 0, -1):
        test = fixed[:end_pos].rstrip()
        if not test:
            continue
        
        # Try to close the array if needed
        candidates = [test]
        
        # If it ends mid-string, try to close it
        if test[-1] not in ']},':
            # Find last complete object
            last_brace = test.rfind('}')
            if last_brace > 0:
                candidates.append(test[:last_brace+1] + '\n]')
        
        if test[-1] == '}':
            candidates.append(test + '\n]')
        
        if test[-1] == ',':
            candidates.append(test[:-1] + '\n]')
        
        for candidate in candidates:
            try:
                data = json.loads(candidate)
                if isinstance(data, list) and len(data) > 0:
                    # Re-write the fixed version
                    with open(filepath, 'w', encoding='utf-8') as f:
                        json.dump(data, f, ensure_ascii=False, indent=2)
                    print(f"✅ {os.path.basename(filepath)}: Fixed! {len(data)} schools recovered")
                    return data
            except:
                continue
    
    print(f"❌ {os.path.basename(filepath)}: Could not auto-fix")
    return None

if __name__ == '__main__':
    data_dir = '/home/luca/.openclaw/workspace-erin/study-abroad-demo/data'
    all_schools = []
    for fname in ['us-schools.json', 'uk-schools.json', 'ca-schools.json']:
        fpath = os.path.join(data_dir, fname)
        if os.path.exists(fpath):
            result = fix_json_file(fpath)
            if result:
                all_schools.extend(result)
    
    print(f"\n📊 Total schools: {len(all_schools)}")
    
    # Write combined file
    combined_path = os.path.join(data_dir, 'all-schools.json')
    with open(combined_path, 'w', encoding='utf-8') as f:
        json.dump(all_schools, f, ensure_ascii=False, indent=2)
    print(f"📦 Combined file written: {combined_path}")
